cluster.name: elasticsearch-cluster
node.name: es-node3
network.host: 0.0.0.0
network.publish_host: 192.168.62.132
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
cluster.initial_master_nodes: es-node1
discovery.zen.ping.unicast.hosts: ["192.168.62.130:9300","192.168.62.131:9300","192.168.62.132:9300"]
discovery.zen.minimum_master_nodes: 2
